# Generated by Django 5.1.4 on 2024-12-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_s1.jpg', upload_to='images/'),
        ),
    ]
