# Generated by Django 5.1.4 on 2024-12-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_s1.jpg', upload_to='images/'),
        ),
    ]
